stages:
  - deploy

deploy:
  image: ruby:latest
  stage: deploy
  before_script:
    - gem install dpl
  only:
    - main
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
